deals/urls.py
from django.conf.urls import url
from deals.views import *

urlpatterns = [
    
    # Full deals page
    # /deals/
    url(r'^$', AllDeals.as_view(), name='index'),

    # Details deal page
    # /deals/<pk>/
    url(r'^(?P<pk>\d+)/$', DetailDeal.as_view(), name='detail')
]

pp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from general.views import Index, About, Contact

urlpatterns = [
    # Admin Urls
    # /admin/*
    url(r'^admin/', admin.site.urls),

    # Index View
    # /
    url(r'^$', Index.as_view(), name='index'),

    # About view
    # /about/
    url(r'^about/$', About.as_view(), name='about'),
    
    # Contact view
    # /contact/
    url(r'^contact/$', Contact.as_view(), name='contact'),
    
    # Games Urls
    # /games/*
    url(r'^games/', include('games.urls', namespace='games')),

    # /sellers/*
    url(r'^sellers/', include('sellers.urls', namespace='sellers')),

    # /sharing/*    
    url(r'^sharing/', include('sharing.urls', namespace='sharing')),

    # /search/*    
    url(r'^search/', include('search.urls', namespace='search')),

    # /deals/*    
    url(r'^deals/', include('deals.urls', namespace='deals')),
    
]

deals/models.py
from django.db import models

class Deal(models.Model):
    
    sellers_list = (
        ('g2a', 'G2a'),
        ('king', 'Kinguin'),
        ('gamestop', 'Gamestop')
    )

    game = models.CharField(max_length=50,
                            null=True,
                            blank=True)
    seller = models.CharField(max_length=50,
                              choices=sellers_list,
                              null=True,
                              blank=True)
    original_price = models.CharField(max_length=4,
                                    null=True,
                                    blank=True)
    current_price = models.CharField(max_length=4,
                                        null = True,
                                        blank=True)
    header_img = models.URLField(
                            null=True,
                            blank=True
    )

    buy_url = models.URLField(
        null=True,
        blank=True
    )

    desc = models.TextField(
        null=True,
        blank=True
    )


    def __str__(self):
        return self.game
    
    def get_ref_url(self):
        if self.buy_url:
            if self.seller == 'king':
                return ''.join([self.buy_url, '?r=42864'])
            else:
                return self.buy_url
        else:
            return ''

deals/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from deals.models import Deal

class AllDeals(ListView):
    ''' Display All Deals '''
    model = Deal
    template_name = 'deals/all.html'


class DetailDeal(DetailView):
    ''' Display one deal in detail '''
    model = Deal
    template_name = 'deals/detail.html'

deals/templates/deals/all.html
{% extends "_layouts/_base.html" %}

{% block extra_css %}
    <style>
        {% for deal in object_list %}
            {% if deal.header_img %}
                #deal-{{deal.pk}}{
                    background: #222222;
                    background-image: url({{deal.header_img}});
                    background-repeat: no-repeat;
                    background-position: center;
                    background-size: 130%;                    
                }
            {% else %}
                #deal-{{deal.pk}} {
                    background: #222222;
                }
            {% endif %}
            
        {% endfor %}
    </style>
{% endblock extra_css %}

{% block content %}

    <div class="grid row">
        <h4 class="title">All Deals</h4>
        {% for deal in object_list %}
            <div class="col-md-4 deal">
                <div class="deal-card" id="deal-{{deal.pk}}">
                    <div class="deal-image">
                        <div class="deal-title">
                            <div class="deal-overlay"></div>
                            <div class="deal-name"><a href="#buynow">{{deal.game}}</a></div>
                            <div class="deal-orig-price">&euro;{{deal.original_price}}</div>
                            <div class="deal-cur-price">&euro;{{deal.current_price}}</div>
                            <div class="deal-cta">
                                <a href="{% url 'deals:detail' deal.pk %}" class="buy_now-btn">Buy Now!</a>
                            </div>
                        </div>                                          
                    </div>
                
                </div>
            </div>
        {% endfor %}
        
    </div>
    
    {% include "_includes/_components/_footer.html" %}

{% endblock content %}  


{% block footer %}

{% endblock footer %}

deals/templates/deals/detail.html
{% extends "_layouts/_base.html" %}

{% block extra_css %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">

    <style>
        .img-head{
            background-image: url({{deal.header_img}});
        }
    </style>
{% endblock extra_css %}

{% block content %}
    <div class="header">
        {% if deal.header_img %}
        <div class="img-head"></div>
        {% else %}
        {% endif %}
        <div class="deal-title">
            <h3>{{deal.game}}</h3>
            <h5 class="deal-cur-price-head">&euro;{{deal.current_price}}</h5>
            <h5 class="deal-orig-price-head">&euro;{{deal.original_price}}</h5>
        </div>
    </div>

    <div class="deal-desc">
        <p>
            {{deal.desc}}
        </p>
    </div>

    <div class="back-options">
            <a href="{% url 'deals:index' %}" class='btn btn-default btn-sm'>
                <i class="material-icons">arrow_back</i>
                <span>
                    Return to all deals
                </span>
            </a>
            <a href="{{deal.get_ref_url}}" class="btn btn-success">Buy Now</a>            
        </div>

{% endblock content %} 